services:
  - type: web
    name: tradeverse-backend
    env: docker
    plan: free
    rootDir: server
    dockerfilePath: ./Dockerfile  # Because Dockerfile is inside server/

  - type: web
    name: tradeverse-frontend
    env: docker
    plan: free
    rootDir: client
    dockerfilePath: ./Dockerfile  # Because Dockerfile is inside client/
