services:
  - type: web
    name: tradeverse-backend
    env: docker
    plan: free
    rootDir: server
    dockerfilePath: Dockerfile
    buildFilter:
      paths:
        - server/**
    autoDeploy: true

  - type: web
    name: tradeverse-frontend
    env: docker
    plan: free
    rootDir: client
    dockerfilePath: Dockerfile
    buildFilter:
      paths:
        - client/**
    autoDeploy: true
